//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDMENUCardManager.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDMENUCardManager.Core.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add game(s).
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [and more {0} folders].
        /// </summary>
        public static string AndMoreFolders {
            get {
                return ResourceManager.GetString("AndMoreFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Rename.
        /// </summary>
        public static string AutomaticallyRename {
            get {
                return ResourceManager.GetString("AutomaticallyRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Rename.
        /// </summary>
        public static string BatchRename {
            get {
                return ResourceManager.GetString("BatchRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load from compressed file..
        /// </summary>
        public static string CantLoadFromCompressedFiles {
            get {
                return ResourceManager.GetString("CantLoadFromCompressedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking.
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Online.
        /// </summary>
        public static string CheckOnline {
            get {
                return ResourceManager.GetString("CheckOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed file.
        /// </summary>
        public static string CompressedFile {
            get {
                return ResourceManager.GetString("CompressedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed Formats.
        /// </summary>
        public static string CompressedFormats {
            get {
                return ResourceManager.GetString("CompressedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion?.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        public static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy name from.
        /// </summary>
        public static string CopyNameFrom {
            get {
                return ResourceManager.GetString("CopyNameFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected as.
        /// </summary>
        public static string DetectedAs {
            get {
                return ResourceManager.GetString("DetectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during GDIShrink.
        /// </summary>
        public static string ErrorDuringGdiShrink {
            get {
                return ResourceManager.GetString("ErrorDuringGdiShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading data.
        /// </summary>
        public static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file {0}.
        /// </summary>
        public static string ErrorLoadingFile {
            get {
                return ResourceManager.GetString("ErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Info.
        /// </summary>
        public static string FileInfo {
            get {
                return ResourceManager.GetString("FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For use with.
        /// </summary>
        public static string ForUseWith {
            get {
                return ResourceManager.GetString("ForUseWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games List.
        /// </summary>
        public static string GamesList {
            get {
                return ResourceManager.GetString("GamesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDI Shrink.
        /// </summary>
        public static string GdiShrink {
            get {
                return ResourceManager.GetString("GdiShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also shrink compressed games.
        /// </summary>
        public static string GdiShrinkCompressedLine1 {
            get {
                return ResourceManager.GetString("GdiShrinkCompressedLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games will be extracted to temp folder prior to shrinking.
        /// </summary>
        public static string GdiShrinkCompressedLine2 {
            get {
                return ResourceManager.GetString("GdiShrinkCompressedLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GDI Shrink for new games.
        /// </summary>
        public static string GdiShrinkLine1 {
            get {
                return ResourceManager.GetString("GdiShrinkLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games can use less space on SD Card.
        /// </summary>
        public static string GdiShrinkLine2 {
            get {
                return ResourceManager.GetString("GdiShrinkLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Blacklist.
        /// </summary>
        public static string GdiShrinkUseBlackListLine1 {
            get {
                return ResourceManager.GetString("GdiShrinkUseBlackListLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skips incompatible games.
        /// </summary>
        public static string GdiShrinkUseBlackListLine2 {
            get {
                return ResourceManager.GetString("GdiShrinkUseBlackListLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored folders/files.
        /// </summary>
        public static string IgnoredFoldersFiles {
            get {
                return ResourceManager.GetString("IgnoredFoldersFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Formats.
        /// </summary>
        public static string ImageFormats {
            get {
                return ResourceManager.GetString("ImageFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoWinTitle {
            get {
                return ResourceManager.GetString("InfoWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Folders.
        /// </summary>
        public static string InvalidFolders {
            get {
                return ResourceManager.GetString("InvalidFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.BIN Info.
        /// </summary>
        public static string IpBinInfo {
            get {
                return ResourceManager.GetString("IpBinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item(s) renamed.
        /// </summary>
        public static string ItemsRenamed {
            get {
                return ResourceManager.GetString("ItemsRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Casing.
        /// </summary>
        public static string LetterCasing {
            get {
                return ResourceManager.GetString("LetterCasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file info.
        /// </summary>
        public static string LoadingFileInfo {
            get {
                return ResourceManager.GetString("LoadingFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Case.
        /// </summary>
        public static string LowerCase {
            get {
                return ResourceManager.GetString("LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made in Brazil.
        /// </summary>
        public static string MadeInBrazil {
            get {
                return ResourceManager.GetString("MadeInBrazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu not selected on Settings.
        /// </summary>
        public static string MenuNotSelectedSettings {
            get {
                return ResourceManager.GetString("MenuNotSelectedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected game(s) down.
        /// </summary>
        public static string MoveSelectedGameDown {
            get {
                return ResourceManager.GetString("MoveSelectedGameDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected game(s) up.
        /// </summary>
        public static string MoveSelectedGameUp {
            get {
                return ResourceManager.GetString("MoveSelectedGameUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Link.
        /// </summary>
        public static string OpenLink {
            get {
                return ResourceManager.GetString("OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled..
        /// </summary>
        public static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preload.
        /// </summary>
        public static string Preload {
            get {
                return ResourceManager.GetString("Preload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load info from files that are already on SD Card.
        /// </summary>
        public static string PreloadTooltip {
            get {
                return ResourceManager.GetString("PreloadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem loading the following folder(s).
        /// </summary>
        public static string ProblemLoadingFollowingFolders {
            get {
                return ResourceManager.GetString("ProblemLoadingFollowingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read TOSEC naming.
        /// </summary>
        public static string ReadTosecNaming {
            get {
                return ResourceManager.GetString("ReadTosecNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Drive List.
        /// </summary>
        public static string RefreshDriveList {
            get {
                return ResourceManager.GetString("RefreshDriveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected game(s).
        /// </summary>
        public static string RemoveSelectedGames {
            get {
                return ResourceManager.GetString("RemoveSelectedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename all games located on.
        /// </summary>
        public static string RenameAllGamesLocatedOn {
            get {
                return ResourceManager.GetString("RenameAllGamesLocatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to {0} drive?.
        /// </summary>
        public static string SaveChangesToDrive {
            get {
                return ResourceManager.GetString("SaveChangesToDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Card.
        /// </summary>
        public static string SdCard {
            get {
                return ResourceManager.GetString("SdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Drive.
        /// </summary>
        public static string SdDrive {
            get {
                return ResourceManager.GetString("SdDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sd Number.
        /// </summary>
        public static string SdNumber {
            get {
                return ResourceManager.GetString("SdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current item folder on SD Card.
        /// </summary>
        public static string SdNumberTooltip {
            get {
                return ResourceManager.GetString("SdNumberTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select games to apply GDI Shrink.
        /// </summary>
        public static string SelectGamesApplyGdiShrink {
            get {
                return ResourceManager.GetString("SelectGamesApplyGdiShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence Case.
        /// </summary>
        public static string SentenceCase {
            get {
                return ResourceManager.GetString("SentenceCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink.
        /// </summary>
        public static string Shrink {
            get {
                return ResourceManager.GetString("Shrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrinking.
        /// </summary>
        public static string Shrinking {
            get {
                return ResourceManager.GetString("Shrinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort List.
        /// </summary>
        public static string SortList {
            get {
                return ResourceManager.GetString("SortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special parsing.
        /// </summary>
        public static string SpecialParsing {
            get {
                return ResourceManager.GetString("SpecialParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support my work.
        /// </summary>
        public static string SupportMyWork {
            get {
                return ResourceManager.GetString("SupportMyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary folder.
        /// </summary>
        public static string TemporaryFolder {
            get {
                return ResourceManager.GetString("TemporaryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following folders need to be deleted..
        /// </summary>
        public static string TheFollowingFoldersNeedDeleted {
            get {
                return ResourceManager.GetString("TheFollowingFoldersNeedDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There might be unused folders/files on the SD Card..
        /// </summary>
        public static string ThereMightBeUnusedFoldersFilesSdCard {
            get {
                return ResourceManager.GetString("ThereMightBeUnusedFoldersFilesSdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool to manage games on.
        /// </summary>
        public static string ToolManageGamesOn {
            get {
                return ResourceManager.GetString("ToolManageGamesOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompressing.
        /// </summary>
        public static string Uncompressing {
            get {
                return ResourceManager.GetString("Uncompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Case.
        /// </summary>
        public static string UpperCase {
            get {
                return ResourceManager.GetString("UpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GDMENU.
        /// </summary>
        public static string UseGDMENU {
            get {
                return ResourceManager.GetString("UseGDMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use openMenu.
        /// </summary>
        public static string UseOpenMenu {
            get {
                return ResourceManager.GetString("UseOpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using File name.
        /// </summary>
        public static string UsingFileName {
            get {
                return ResourceManager.GetString("UsingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Folder name.
        /// </summary>
        public static string UsingFolderName {
            get {
                return ResourceManager.GetString("UsingFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using IP.BIN _info.
        /// </summary>
        public static string UsingIPBIN {
            get {
                return ResourceManager.GetString("UsingIPBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View File Info.
        /// </summary>
        public static string ViewFileInfo {
            get {
                return ResourceManager.GetString("ViewFileInfo", resourceCulture);
            }
        }
    }
}
